#############################################################################
# Makefile for building: QBZ.app/Contents/MacOS/QBZ
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Sep 18 20:08:16 2011
# Project:  QBZ.pro
# Template: app
# Command: /Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile QBZ.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DECLARATIVE_LIB -DQT_SCRIPT_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -I. -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtDesigner.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtDesigner -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtOpenGL -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtXml.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtXml -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtScript.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtScript -I../../QtSDK/Desktop/Qt/474/gcc/lib/QtDeclarative.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/474/gcc/include/QtDeclarative -I../../QtSDK/Desktop/Qt/474/gcc/include -I. -Isrc -I/usr/include -I/usr/local/include -I/usr/include -I/usr/local/include -I/opt/local/include -Iframeworks -Iframeworks/cpptweener/src -Iframeworks/assimp/include -Iframeworks/CLAM/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Users/krs/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/krs/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/krs/QtSDK/Desktop/Qt/474/gcc/lib -framework CoreMidi -framework CoreAudio -framework CoreFoundation -framework CoreServices -framework Appkit -framework Cocoa -framework ApplicationServices -framework AudioToolbox -Lframeworks/assimp/lib -lassimp /Users/krs/QtSDK/Desktop/Qt/474/gcc/lib/libQtUiTools.a -framework QtDeclarative -framework QtScript -framework QtXml -framework QtOpenGL -framework QtGui -framework QtCore -framework QtDesigner -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/qbz_midithread.cpp \
		src/qbz_deferredrenderer.cpp \
		src/qbz_skybox.cpp \
		src/qbz_ofwidget.cpp \
		src/qbz_composer.cpp \
		src/qbz_world.cpp \
		src/qbz_renderprogram.cpp \
		src/qbz_animator.cpp \
		src/qbz_fbo.cpp \
		src/qbz_shader.cpp \
		src/qbz_lightdot.cpp \
		src/qbz_model.cpp \
		src/qbz_mesh.cpp \
		src/qbz_camera.cpp \
		src/qbz_projection_simple.cpp \
		src/qbz_projectionarea.cpp \
		src/mainwindow.cpp \
		src/RtMidi.cpp \
		frameworks/cpptweener/src/CppTweener.cpp \
		src/qbz_glthread.cpp \
		qbz_renderwidget.cpp \
		src/qbz_particlebase.cpp \
		src/qbz_terrain.cpp \
		src/qbz_vbo.cpp \
		src/qbz_library.cpp \
		src/qbz_depthfbo.cpp \
		src/qbz_harmonics.cpp \
		src/qbz_network.cpp \
		src/rendertarget.cpp \
		src/registry.cpp moc_qbz_midithread.cpp \
		moc_qbz_ofwidget.cpp \
		moc_mainwindow.cpp \
		moc_qbz_glthread.cpp \
		moc_qbz_renderwidget.cpp \
		qrc_QBZ.cpp
OBJECTS       = main.o \
		qbz_midithread.o \
		qbz_deferredrenderer.o \
		qbz_skybox.o \
		qbz_ofwidget.o \
		qbz_composer.o \
		qbz_world.o \
		qbz_renderprogram.o \
		qbz_animator.o \
		qbz_fbo.o \
		qbz_shader.o \
		qbz_lightdot.o \
		qbz_model.o \
		qbz_mesh.o \
		qbz_camera.o \
		qbz_projection_simple.o \
		qbz_projectionarea.o \
		mainwindow.o \
		RtMidi.o \
		CppTweener.o \
		qbz_glthread.o \
		qbz_renderwidget.o \
		qbz_particlebase.o \
		qbz_terrain.o \
		qbz_vbo.o \
		qbz_library.o \
		qbz_depthfbo.o \
		qbz_harmonics.o \
		qbz_network.o \
		rendertarget.o \
		registry.o \
		moc_qbz_midithread.o \
		moc_qbz_ofwidget.o \
		moc_mainwindow.o \
		moc_qbz_glthread.o \
		moc_qbz_renderwidget.o \
		qrc_QBZ.o
DIST          = ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/designer.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		QBZ.pro
QMAKE_TARGET  = QBZ
DESTDIR       = 
TARGET        = QBZ.app/Contents/MacOS/QBZ

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QBZ.app/Contents/PkgInfo QBZ.app/Contents/Resources/empty.lproj QBZ.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QBZ.app/Contents/MacOS/ || $(MKDIR) QBZ.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QBZ.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/designer.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile QBZ.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/designer.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/opengl.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile QBZ.pro

QBZ.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QBZ.app/Contents || $(MKDIR) QBZ.app/Contents 
	@$(DEL_FILE) QBZ.app/Contents/PkgInfo
	@echo "APPL????" >QBZ.app/Contents/PkgInfo
QBZ.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) QBZ.app/Contents/Resources || $(MKDIR) QBZ.app/Contents/Resources 
	@touch QBZ.app/Contents/Resources/empty.lproj
	
QBZ.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QBZ.app/Contents || $(MKDIR) QBZ.app/Contents 
	@$(DEL_FILE) QBZ.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QBZ,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++/Info.plist.app >QBZ.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/QBZ1.0.0 || $(MKDIR) .tmp/QBZ1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QBZ1.0.0/ && $(COPY_FILE) --parents src/qbz.h src/qbz_midithread.h src/qbz_baseapp.h src/qbz_skybox.h src/qbz_deferredrenderer.h src/qbz_ofwidget.h src/qbz_composer.h src/qbz_world.h src/qbz_renderprogram.h src/qbz_animator.h src/qbz_fbo.h src/qbz_shader.h src/qbz_lightdot.h src/qbz_model.h src/qbz_mesh.h src/qbz_camera.h src/qbz_projection_simple.h src/qbz_projectionarea.h src/mainwindow.h src/RtMidi.h src/RtError.h frameworks/cpptweener/src/CppTweener.h src/qbz_glthread.h qbz_renderwidget.h src/qbz_particlebase.h src/qbz_terrain.h src/qbz_vbo.h src/qbz_library.h src/qbz_depthfbo.h src/qbz_harmonics.h src/qbz_network.h src/rendertarget.h src/registry.h .tmp/QBZ1.0.0/ && $(COPY_FILE) --parents QBZ.qrc .tmp/QBZ1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/qbz_midithread.cpp src/qbz_deferredrenderer.cpp src/qbz_skybox.cpp src/qbz_ofwidget.cpp src/qbz_composer.cpp src/qbz_world.cpp src/qbz_renderprogram.cpp src/qbz_animator.cpp src/qbz_fbo.cpp src/qbz_shader.cpp src/qbz_lightdot.cpp src/qbz_model.cpp src/qbz_mesh.cpp src/qbz_camera.cpp src/qbz_projection_simple.cpp src/qbz_projectionarea.cpp src/mainwindow.cpp src/RtMidi.cpp frameworks/cpptweener/src/CppTweener.cpp src/qbz_glthread.cpp qbz_renderwidget.cpp src/qbz_particlebase.cpp src/qbz_terrain.cpp src/qbz_vbo.cpp src/qbz_library.cpp src/qbz_depthfbo.cpp src/qbz_harmonics.cpp src/qbz_network.cpp src/rendertarget.cpp src/registry.cpp .tmp/QBZ1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui .tmp/QBZ1.0.0/ && (cd `dirname .tmp/QBZ1.0.0` && $(TAR) QBZ1.0.0.tar QBZ1.0.0 && $(COMPRESS) QBZ1.0.0.tar) && $(MOVE) `dirname .tmp/QBZ1.0.0`/QBZ1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QBZ1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QBZ.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_qbz_midithread.cpp moc_qbz_ofwidget.cpp moc_mainwindow.cpp moc_qbz_glthread.cpp moc_qbz_renderwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qbz_midithread.cpp moc_qbz_ofwidget.cpp moc_mainwindow.cpp moc_qbz_glthread.cpp moc_qbz_renderwidget.cpp
moc_qbz_midithread.cpp: src/qbz.h \
		src/RtMidi.h \
		src/RtError.h \
		src/qbz_midithread.h
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/qbz_midithread.h -o moc_qbz_midithread.cpp

moc_qbz_ofwidget.cpp: src/qbz.h \
		src/qbz_composer.h \
		src/qbz_network.h \
		src/qbz_ofwidget.h
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/qbz_ofwidget.h -o moc_qbz_ofwidget.cpp

moc_mainwindow.cpp: src/qbz.h \
		src/qbz_ofwidget.h \
		src/qbz_composer.h \
		src/qbz_network.h \
		src/mainwindow.h
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/mainwindow.h -o moc_mainwindow.cpp

moc_qbz_glthread.cpp: src/qbz_glthread.h
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/qbz_glthread.h -o moc_qbz_glthread.cpp

moc_qbz_renderwidget.cpp: qbz_renderwidget.h
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qbz_renderwidget.h -o moc_qbz_renderwidget.cpp

compiler_rcc_make_all: qrc_QBZ.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QBZ.cpp
qrc_QBZ.cpp: QBZ.qrc \
		foo.qml \
		ui/mainwindow.ui
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name QBZ QBZ.qrc -o qrc_QBZ.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui
	/Users/krs/QtSDK/Desktop/Qt/474/gcc/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/qbz.h \
		src/qbz_ofwidget.h \
		src/qbz_composer.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qbz_midithread.o: src/qbz_midithread.cpp src/qbz_midithread.h \
		src/qbz.h \
		src/RtMidi.h \
		src/RtError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_midithread.o src/qbz_midithread.cpp

qbz_deferredrenderer.o: src/qbz_deferredrenderer.cpp src/qbz_deferredrenderer.h \
		src/qbz.h \
		src/qbz_network.h \
		src/qbz_world.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_deferredrenderer.o src/qbz_deferredrenderer.cpp

qbz_skybox.o: src/qbz_skybox.cpp src/qbz_skybox.h \
		src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_skybox.o src/qbz_skybox.cpp

qbz_ofwidget.o: src/qbz_ofwidget.cpp src/qbz_ofwidget.h \
		src/qbz.h \
		src/qbz_composer.h \
		src/qbz_network.h \
		src/qbz_midithread.h \
		src/RtMidi.h \
		src/RtError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_ofwidget.o src/qbz_ofwidget.cpp

qbz_composer.o: src/qbz_composer.cpp src/qbz_composer.h \
		src/qbz.h \
		src/qbz_network.h \
		src/qbz_library.h \
		src/qbz_animator.h \
		src/qbz_world.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_renderprogram.h \
		src/qbz_deferredrenderer.h \
		src/qbz_projection_simple.h \
		src/qbz_fbo.h \
		src/qbz_projectionarea.h \
		src/qbz_harmonics.h \
		src/rendertarget.h \
		src/qbz_skybox.h \
		src/qbz_terrain.h \
		src/mainwindow.h \
		src/qbz_ofwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_composer.o src/qbz_composer.cpp

qbz_world.o: src/qbz_world.cpp src/qbz_world.h \
		src/qbz.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h \
		src/qbz_renderprogram.h \
		src/qbz_light.h \
		src/qbz_projection_simple.h \
		src/qbz_projectionarea.h \
		src/qbz_tgatexture.h \
		src/qbz_fbo.h \
		src/qbz_lightdot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_world.o src/qbz_world.cpp

qbz_renderprogram.o: src/qbz_renderprogram.cpp src/qbz_renderprogram.h \
		src/qbz.h \
		src/qbz_network.h \
		src/qbz_shader.h \
		src/qbz_camera.h \
		src/qbz_mesh.h \
		src/qbz_model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_renderprogram.o src/qbz_renderprogram.cpp

qbz_animator.o: src/qbz_animator.cpp src/qbz_animator.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_animator.o src/qbz_animator.cpp

qbz_fbo.o: src/qbz_fbo.cpp src/qbz_fbo.h \
		src/qbz.h \
		src/qbz_renderprogram.h \
		src/qbz_network.h \
		src/qbz_projection_simple.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_fbo.o src/qbz_fbo.cpp

qbz_shader.o: src/qbz_shader.cpp src/qbz_shader.h \
		src/qbz.h \
		src/mainwindow.h \
		src/qbz_ofwidget.h \
		src/qbz_composer.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_shader.o src/qbz_shader.cpp

qbz_lightdot.o: src/qbz_lightdot.cpp src/qbz_lightdot.h \
		src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_lightdot.o src/qbz_lightdot.cpp

qbz_model.o: src/qbz_model.cpp src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_model.o src/qbz_model.cpp

qbz_mesh.o: src/qbz_mesh.cpp src/qbz_mesh.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_mesh.o src/qbz_mesh.cpp

qbz_camera.o: src/qbz_camera.cpp src/qbz_camera.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_camera.o src/qbz_camera.cpp

qbz_projection_simple.o: src/qbz_projection_simple.cpp src/qbz_projection_simple.h \
		src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_projection_simple.o src/qbz_projection_simple.cpp

qbz_projectionarea.o: src/qbz_projectionarea.cpp src/qbz_projectionarea.h \
		src/qbz.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_projectionarea.o src/qbz_projectionarea.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/qbz.h \
		src/qbz_ofwidget.h \
		src/qbz_composer.h \
		src/qbz_network.h \
		qbz_renderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

RtMidi.o: src/RtMidi.cpp src/RtMidi.h \
		src/RtError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RtMidi.o src/RtMidi.cpp

CppTweener.o: frameworks/cpptweener/src/CppTweener.cpp frameworks/cpptweener/src/CppTweener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CppTweener.o frameworks/cpptweener/src/CppTweener.cpp

qbz_glthread.o: src/qbz_glthread.cpp src/qbz_glthread.h \
		qbz_renderwidget.h \
		src/qbz_composer.h \
		src/qbz.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_glthread.o src/qbz_glthread.cpp

qbz_renderwidget.o: qbz_renderwidget.cpp qbz_renderwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_renderwidget.o qbz_renderwidget.cpp

qbz_particlebase.o: src/qbz_particlebase.cpp src/qbz_particlebase.h \
		src/qbz.h \
		src/qbz_model.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h \
		src/qbz_renderprogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_particlebase.o src/qbz_particlebase.cpp

qbz_terrain.o: src/qbz_terrain.cpp src/qbz_terrain.h \
		src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_terrain.o src/qbz_terrain.cpp

qbz_vbo.o: src/qbz_vbo.cpp src/qbz_vbo.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_vbo.o src/qbz_vbo.cpp

qbz_library.o: src/qbz_library.cpp src/qbz_library.h \
		src/qbz.h \
		src/qbz_tgatexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_library.o src/qbz_library.cpp

qbz_depthfbo.o: src/qbz_depthfbo.cpp src/qbz_depthfbo.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_depthfbo.o src/qbz_depthfbo.cpp

qbz_harmonics.o: src/qbz_harmonics.cpp src/qbz_harmonics.h \
		src/qbz_model.h \
		src/qbz.h \
		src/qbz_shader.h \
		src/qbz_mesh.h \
		src/qbz_camera.h \
		src/qbz_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_harmonics.o src/qbz_harmonics.cpp

qbz_network.o: src/qbz_network.cpp src/qbz_network.h \
		src/qbz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbz_network.o src/qbz_network.cpp

rendertarget.o: src/rendertarget.cpp src/rendertarget.h \
		src/qbz.h \
		src/qbz_network.h \
		src/qbz_renderprogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rendertarget.o src/rendertarget.cpp

registry.o: src/registry.cpp src/registry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registry.o src/registry.cpp

moc_qbz_midithread.o: moc_qbz_midithread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbz_midithread.o moc_qbz_midithread.cpp

moc_qbz_ofwidget.o: moc_qbz_ofwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbz_ofwidget.o moc_qbz_ofwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qbz_glthread.o: moc_qbz_glthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbz_glthread.o moc_qbz_glthread.cpp

moc_qbz_renderwidget.o: moc_qbz_renderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qbz_renderwidget.o moc_qbz_renderwidget.cpp

qrc_QBZ.o: qrc_QBZ.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QBZ.o qrc_QBZ.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

